dic =     {
    "instruction": "Provide the optimal FCU fan speed settings for each room based on the current room temperatures, FCU feedback, occupant numbers, and outdoor temperature.",
    "input": "Timestamp index: 599 (August 9th, 18:59am/pm).\nCurrent building conditions:\n--- Outdoor Environment Status ---\n- Outdoor Temperature: 26.90\u00b0C\n--- Room 1 Status ---\n- Room Temp: 18.83\u00b0C\n- Fcu Fan Feedback: 2\n- Supply Temp: 7.00\u00b0C\n- Return Temp: 7.19\u00b0C\n- Occupant Num: {'sitting': 1, 'walking': 0, 'standing': 0}\n--- Room 2 Status ---\n- Room Temp: 18.28\u00b0C\n- Fcu Fan Feedback: 2\n- Supply Temp: 7.00\u00b0C\n- Return Temp: 8.04\u00b0C\n- Occupant Num: {'sitting': 0, 'walking': 0, 'standing': 0}\n--- Room 3 Status ---\n- Room Temp: 19.82\u00b0C\n- Fcu Fan Feedback: 1\n- Supply Temp: 7.00\u00b0C\n- Return Temp: 8.20\u00b0C\n- Occupant Num: {'sitting': 1, 'walking': 0, 'standing': 0}\n--- Room 4 Status ---\n- Room Temp: 21.49\u00b0C\n- Fcu Fan Feedback: 0\n- Supply Temp: 7.00\u00b0C\n- Return Temp: 7.00\u00b0C\n- Occupant Num: {'sitting': 1, 'walking': 0, 'standing': 0}\n--- Room 5 Status ---\n- Room Temp: 21.37\u00b0C\n- Fcu Fan Feedback: 0\n- Supply Temp: 7.00\u00b0C\n- Return Temp: 7.00\u00b0C\n- Occupant Num: {'sitting': 0, 'walking': 0, 'standing': 0}\n--- Room 6 Status ---\n- Room Temp: 22.23\u00b0C\n- Fcu Fan Feedback: 1\n- Supply Temp: 7.00\u00b0C\n- Return Temp: 7.85\u00b0C\n- Occupant Num: {'sitting': 1, 'walking': 0, 'standing': 0}\n--- Room 7 Status ---\n- Room Temp: 22.47\u00b0C\n- Fcu Fan Feedback: 1\n- Supply Temp: 7.00\u00b0C\n- Return Temp: 8.78\u00b0C\n- Occupant Num: {'sitting': 1, 'walking': 0, 'standing': 0}\n",
    "output": "Execute the following FCU fan speed control actions for all rooms:\n--- Room 1 FCU Fan Controls ---\n- Set FCU Fan Speed: 2\n--- Room 2 FCU Fan Controls ---\n- Set FCU Fan Speed: 2\n--- Room 3 FCU Fan Controls ---\n- Set FCU Fan Speed: 1\n--- Room 4 FCU Fan Controls ---\n- Set FCU Fan Speed: 0\n--- Room 5 FCU Fan Controls ---\n- Set FCU Fan Speed: 0\n--- Room 6 FCU Fan Controls ---\n- Set FCU Fan Speed: 1\n--- Room 7 FCU Fan Controls ---\n- Set FCU Fan Speed: 1\n",
    "system": "You are an expert AI assistant for building management systems.\nYour task is to analyze current and historical room and outdoor sensor data to provide precise FCU fan speed control commands for each room, optimizing for occupant comfort and energy efficiency.\n\n### Scenario Setting\n- **Season:** Summer. The primary goal of the HVAC system is to cool the rooms.\n- **HVAC Effect:** A higher FCU Fan Speed setting (e.g., from 1 to 3) results in stronger cooling and a lower indoor temperature. A setting of 0 means the fan is off.\n- **Occupant Comfort Preferences:** The target comfort temperature varies by the occupants' primary activity:\n  - **Sitting:** Optimal comfort temperature is approximately 26\u63b3C.\n  - **Walking:** Optimal comfort temperature is approximately 24\u63b3C.\n  - **Standing:** Optimal comfort temperature is approximately 25\u63b3C.\n\n### Building Configuration\n- The building consists of 7 rooms.\n- **Rooms 1, 2, 3, 4:** These are independent offices. Control actions in one of these rooms primarily affect only that room.\n- **Rooms 5, 6, 7:** These three rooms form a single, large, interconnected hall. Control actions in one of these rooms will influence the temperature and conditions in the other two due to air mixing.\n\n### Variable Definitions\n- **Outdoor Temperature:** The current temperature outside the building.\n- **Room Temperature:** The current air temperature inside a specific room.\n- **FCU Fan Feedback:** The current operational fan speed (gear) of the Fan Coil Unit. The range is integers: 0 (Off), 1 (Low), 2 (Medium), 3 (High).\n- **Supply Temp & Return Temp:** These are the temperatures of the chilled water supplied to and returning from the FCU. For example, `Supply Temp: 7.00\u63b3C - Return Temp: 7.85\u63b3C`. A larger difference indicates more heat is being removed from the room.\n- **Occupant Num:** A dictionary showing the number of people and their primary activity. Example: `{'sitting': 2, 'walking': 1, 'standing': 0}`.",
    "history": []
  }

# dict2 = {
#     "instruction": "Considering the historical context and current conditions, provide the optimal FCU fan speed settings for each room.",
#     "input": "Timestamp index: 5 (August 9th, 9:05am/pm).\nCurrent building conditions:\n--- Outdoor Environment Status ---\n- Outdoor Temperature: 24.21\u00b0C\n--- Room 1 Status ---\n- Room Temp: 25.34\u00b0C\n- Fcu Fan Feedback: 2\n- Supply Temp: 7.00\u00b0C\n- Return Temp: 7.44\u00b0C\n- Occupant Num: {'sitting': 0, 'walking': 0, 'standing': 0}\n--- Room 2 Status ---\n- Room Temp: 25.34\u00b0C\n- Fcu Fan Feedback: 2\n- Supply Temp: 7.00\u00b0C\n- Return Temp: 9.78\u00b0C\n- Occupant Num: {'sitting': 0, 'walking': 0, 'standing': 0}\n--- Room 3 Status ---\n- Room Temp: 27.94\u00b0C\n- Fcu Fan Feedback: 0\n- Supply Temp: 7.00\u00b0C\n- Return Temp: 7.00\u00b0C\n- Occupant Num: {'sitting': 0, 'walking': 0, 'standing': 0}\n--- Room 4 Status ---\n- Room Temp: 25.07\u00b0C\n- Fcu Fan Feedback: 1\n- Supply Temp: 7.00\u00b0C\n- Return Temp: 9.57\u00b0C\n- Occupant Num: {'sitting': 0, 'walking': 0, 'standing': 0}\n--- Room 5 Status ---\n- Room Temp: 24.83\u00b0C\n- Fcu Fan Feedback: 3\n- Supply Temp: 7.00\u00b0C\n- Return Temp: 8.95\u00b0C\n- Occupant Num: {'sitting': 0, 'walking': 0, 'standing': 0}\n--- Room 6 Status ---\n- Room Temp: 25.56\u00b0C\n- Fcu Fan Feedback: 0\n- Supply Temp: 7.00\u00b0C\n- Return Temp: 7.00\u00b0C\n- Occupant Num: {'sitting': 0, 'walking': 0, 'standing': 0}\n--- Room 7 Status ---\n- Room Temp: 25.23\u00b0C\n- Fcu Fan Feedback: 1\n- Supply Temp: 7.00\u00b0C\n- Return Temp: 9.36\u00b0C\n- Occupant Num: {'sitting': 0, 'walking': 0, 'standing': 0}\n",
#     "output": "Execute the following FCU fan speed control actions for all rooms:\n--- Room 1 FCU Fan Controls ---\n- Set FCU Fan Speed: 2\n--- Room 2 FCU Fan Controls ---\n- Set FCU Fan Speed: 2\n--- Room 3 FCU Fan Controls ---\n- Set FCU Fan Speed: 0\n--- Room 4 FCU Fan Controls ---\n- Set FCU Fan Speed: 1\n--- Room 5 FCU Fan Controls ---\n- Set FCU Fan Speed: 3\n--- Room 6 FCU Fan Controls ---\n- Set FCU Fan Speed: 0\n--- Room 7 FCU Fan Controls ---\n- Set FCU Fan Speed: 1\n",
#     "system": "You are an expert AI assistant for building management systems.\nYour task is to analyze current and historical room and outdoor sensor data to provide precise FCU fan speed control commands for each room, optimizing for occupant comfort and energy efficiency.\n\n### Scenario Setting\n- **Season:** Summer. The primary goal of the HVAC system is to cool the rooms.\n- **HVAC Effect:** A higher FCU Fan Speed setting (e.g., from 1 to 3) results in stronger cooling and a lower indoor temperature. A setting of 0 means the fan is off.\n- **Occupant Comfort Preferences:** The target comfort temperature varies by the occupants' primary activity:\n  - **Sitting:** Optimal comfort temperature is approximately 26\u63b3C.\n  - **Walking:** Optimal comfort temperature is approximately 24\u63b3C.\n  - **Standing:** Optimal comfort temperature is approximately 25\u63b3C.\n\n### Building Configuration\n- The building consists of 7 rooms.\n- **Rooms 1, 2, 3, 4:** These are independent offices. Control actions in one of these rooms primarily affect only that room.\n- **Rooms 5, 6, 7:** These three rooms form a single, large, interconnected hall. Control actions in one of these rooms will influence the temperature and conditions in the other two due to air mixing.\n\n### Variable Definitions\n- **Outdoor Temperature:** The current temperature outside the building.\n- **Room Temperature:** The current air temperature inside a specific room.\n- **FCU Fan Feedback:** The current operational fan speed (gear) of the Fan Coil Unit. The range is integers: 0 (Off), 1 (Low), 2 (Medium), 3 (High).\n- **Supply Temp & Return Temp:** These are the temperatures of the chilled water supplied to and returning from the FCU. For example, `Supply Temp: 7.00\u63b3C - Return Temp: 7.85\u63b3C`. A larger difference indicates more heat is being removed from the room.\n- **Occupant Num:** A dictionary showing the number of people and their primary activity. Example: `{'sitting': 2, 'walking': 1, 'standing': 0}`.",
#     "history": [
#       [
#         "This was the situation at timestep 2. What action was taken?",
#         "Status at timestep 2:\n- Outdoor Temp: 24.21\u00b0C\n- Room 1: Temp=25.98\u00b0C, Fan Speed=2, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 2: Temp=25.98\u00b0C, Fan Speed=2, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 3: Temp=27.09\u00b0C, Fan Speed=0, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 4: Temp=25.88\u00b0C, Fan Speed=1, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 5: Temp=25.77\u00b0C, Fan Speed=3, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 6: Temp=26.10\u00b0C, Fan Speed=0, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 7: Temp=25.95\u00b0C, Fan Speed=1, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\nAction taken:\n- Room 1 Fan Setpoint: 2\n- Room 2 Fan Setpoint: 2\n- Room 3 Fan Setpoint: 0\n- Room 4 Fan Setpoint: 1\n- Room 5 Fan Setpoint: 3\n- Room 6 Fan Setpoint: 0\n- Room 7 Fan Setpoint: 1\n"
#       ],
#       [
#         "This was the situation at timestep 3. What action was taken?",
#         "Status at timestep 3:\n- Outdoor Temp: 24.21\u00b0C\n- Room 1: Temp=25.75\u00b0C, Fan Speed=2, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 2: Temp=25.75\u00b0C, Fan Speed=2, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 3: Temp=27.38\u00b0C, Fan Speed=0, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 4: Temp=25.59\u00b0C, Fan Speed=1, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 5: Temp=25.44\u00b0C, Fan Speed=3, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 6: Temp=25.91\u00b0C, Fan Speed=0, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 7: Temp=25.70\u00b0C, Fan Speed=1, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\nAction taken:\n- Room 1 Fan Setpoint: 2\n- Room 2 Fan Setpoint: 2\n- Room 3 Fan Setpoint: 0\n- Room 4 Fan Setpoint: 1\n- Room 5 Fan Setpoint: 3\n- Room 6 Fan Setpoint: 0\n- Room 7 Fan Setpoint: 1\n"
#       ],
#       [
#         "This was the situation at timestep 4. What action was taken?",
#         "Status at timestep 4:\n- Outdoor Temp: 24.21\u00b0C\n- Room 1: Temp=25.54\u00b0C, Fan Speed=2, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 2: Temp=25.54\u00b0C, Fan Speed=2, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 3: Temp=27.66\u00b0C, Fan Speed=0, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 4: Temp=25.33\u00b0C, Fan Speed=1, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 5: Temp=25.13\u00b0C, Fan Speed=3, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 6: Temp=25.73\u00b0C, Fan Speed=0, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\n- Room 7: Temp=25.46\u00b0C, Fan Speed=1, Occupants={'sitting': 0, 'walking': 0, 'standing': 0}\nAction taken:\n- Room 1 Fan Setpoint: 2\n- Room 2 Fan Setpoint: 2\n- Room 3 Fan Setpoint: 0\n- Room 4 Fan Setpoint: 1\n- Room 5 Fan Setpoint: 3\n- Room 6 Fan Setpoint: 0\n- Room 7 Fan Setpoint: 1\n"
#       ]
#     ]
#   }


# print(dict2["system"])
print(dic["output"])
